### ISSUE TITLE
1.0.0 release broken against current dependencies -- new release required

### ISSUE THREAD

**Issue by ugexe** [croservices/cro-openapi-routes-from-definition#6]
A new release that includes https://github.com/croservices/cro-openapi-routes-from-definition/commit/12c03258bb1b4efea11f1266022097ba9547f8b2 is required to fix installation.

```
===> Install [FAIL] for Cro::OpenAPI::RoutesFromDefinition:ver<1.0.0>: ===SORRY!=== Error while compiling /Users/ugexe/repos/Perl6-App--Zef--WebAPI/site#sources/758048F4C0F641D7762FF6CAF577C27866846F03 (Cro::OpenAPI::RoutesFromDefinition)
Attribute @!after not declared in class Cro::OpenAPI::RoutesFromDefinition::OperationSet::OperationHandler
at /Users/ugexe/repos/Perl6-App--Zef--WebAPI/site#sources/758048F4C0F641D7762FF6CAF577C27866846F03 (Cro::OpenAPI::RoutesFromDefinition):311
------>         }⏏<EOL>
```

**Comment by patzim** [comment]
I'm waiting for this.
Version 1.0.1 is already set in the repo. Only the actual release on CPAN is missing.
@jnthn You did the release last time, so I suspect you are the right person to poke.

**Comment by jnthn** [comment]
Sorry for the delay; the new release is uploaded.
