### ISSUE TITLE
Something broke on latest rakudo?

### ISSUE THREAD

**Issue by CurtTilmes** [croservices/cro-openapi-routes-from-definition#8]
I upgraded my rakudo and openapi tests started failing in my app.

I was able to re-create from the current rakudo-star docker:

```
docker run -it --entrypoint /bin/sh rakudo-star
```
which looks up to date:
```
# perl6 -v
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.
```

Then install libssl:
```
apt update
apt install -y libssl1.0-dev
```
Then install Cro::OpenAPI::RoutesFromDefinition:

```
zef install Cro::OpenAPI::RoutesFromDefinition
```

Which fails most of the tests, which used to succeed.

**Comment by Altai-man** [comment]
Can confirm, but cannot do anything other.
It seems to me like a regression ticket for Rakudo, though, not this repo. It should be bisected and investigated there.

**Comment by jnthn** [comment]
Please file this against Rakudo, where it will likely be considered a release blocker (although in theory the automated module testing should also pick it up).

**Comment by jnthn** [comment]
Also: there was another regression related to `Parameter` changes, though I can't immediately find the Rakudo issue. But since this module I believe also subclasses `Parameter`, it's possibly connected to that.

**Comment by CurtTilmes** [comment]
Looks like this: https://github.com/rakudo/rakudo/issues/2829
